### ISSUE TITLE
Something unsual happened

### ISSUE THREAD

**Issue by francesco-girardi** [retlat/Connect-PostgreSQL-from-Android#1]
Hello i tried to copy this in my android java app but it run into this somenthing unusaul failed happend what i did wrong?

`W/System.err: org.postgresql.util.PSQLException: Qualcosa di insolito si è verificato causando il fallimento del driver. Per favore riferire all'autore del driver questa eccezione.
W/System.err:     at org.postgresql.Driver.connect(Driver.java:282)
W/System.err:     at java.sql.DriverManager.getConnection(DriverManager.java:580)
        at java.sql.DriverManager.getConnection(DriverManager.java:218)
        at com.bluetigers.balancemanagerapp.utils.DatabaseConnection.setConnection(DatabaseConnection.java:60)
        at com.bluetigers.balancemanagerapp.utils.DatabaseConnection.<init>(DatabaseConnection.java:24)
        at com.bluetigers.balancemanagerapp.HomeActivity.onCreate(HomeActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:8086)
        at android.app.Activity.performCreate(Activity.java:8074)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
W/System.err: Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:389)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at org.postgresql.core.PGStream.<init>(PGStream.java:81)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:92)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:196)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
        at org.postgresql.Driver.makeConnection(Driver.java:459)
        at org.postgresql.Driver.connect(Driver.java:261)
    	... 20 more`

This below is my code: 
`String URL = "jdbc:postgresql://xx.xx.xx.xx:5432/balance_manager";
        try {
            connection = DriverManager.getConnection(URL, "francesco", "Rosita98!");
            Log.v("DatabaseConnection", "dbConnection: Connected!");
        } catch (SQLException throwables) {
            throwables.printStackTrace();
            Log.v("DatabaseConnection", "dbConnection: " + throwables);
        }`

**Comment by retlat** [comment]
It looks like you tried to open connection on main thread.
> W/System.err: Caused by: android.os.NetworkOnMainThreadException at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)

You should run network operation on the thread which is not main by using java.lang.Thread, java.util.concurrent, Kotlin coroutines and so on.
